---
- hosts: lxc
  sudo: yes
  tasks:
    - action: apt pkg=software-properties-common state=present
    - action: apt_repository repo=ppa:rethinkdb/ppa
    - action: apt pkg=rethinkdb state=present
    - command: cp /etc/rethinkdb/default.conf.sample /etc/rethinkdb/instances.d/default.conf creates=/etc/rethinkdb/instances.d/default.conf

    - action: apt_repository repo=ppa:dotcloud/lxc-docker
    - action: apt pkg=lxc-docker state=present
